### ISSUE TITLE
Animated Truck Reaction

### ISSUE THREAD

**Issue by sensible-heart** [sensible-heart/ProducePanic#12]
We want the driver of the truck to smile when good food in dropped into the truck and frown when bad food makes it through. The truck will also have it's food pile grow as more food is dropped into it. More than 75% Good fruit will show a good fruit pile, 25%-75% will show a mixed pile, and <25% will show a bad fruit pile.

**Comment by wrflemin** [comment]
This has been completed as mentioned above. If we have extra time we may want to animate the sprite transitions, but its not a simple function call to do so. Will reopen if required/desired.
